### ISSUE TITLE
Matching tests to main repo

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#2]
I'm a bit late to the party in trying to make sure this works for me, but I'm finally looking into it.  To that end, I'm having some trouble figuring out which commit of the main repository the most recent commit here is supposed to pass.

Could a notation be added somewhere which identifies the commit in the main repository which is expected to pass all of the tests?  This could be as simple as a note in the README.md which is manually updated when the tests are modified.

**Comment by henryso** [comment]
I don't think gregorio-test has ever matched the master branch of gregorio.  It was started in the middle of 3.0 development against the develop branch.  Going forward, we need to have more structure to make the branches match, but we are actually not past the gestation period, which will end at the next release.

**Comment by rpspringuel** [comment]
I get that this is supposed to match against develop and not master, but which commit on develop?

**Comment by rpspringuel** [comment]
Right now I'd settle for a single data point so that I can tell that the test suite is working properly.

**Comment by henryso** [comment]
gregorio-test should match the current develop as of now.  However, what I'm afraid of is the PDF tests differing ever so slightly, so thanks for testing.

**Comment by rpspringuel** [comment]
Okay, I'm getting a boat load of failures against `3.0.1-develop-bb48b95-2037`

To wit:
```
Gregorio = /usr/local/bin/gregorio
GregorioTeX = /usr/local/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex.tex

gabc-gtex/bugs/fix-135.gabc : FAIL - Files gabc-gtex/bugs/fix-135.gabc.out- and gabc-gtex/bugs/fix-135.tex- differ
gabc-gtex/bugs/fix-42-a.gabc : FAIL - Files gabc-gtex/bugs/fix-42-a.gabc.out- and gabc-gtex/bugs/fix-42-a.tex- differ
gabc-gtex/bugs/fix-42-b.gabc : FAIL - Files gabc-gtex/bugs/fix-42-b.gabc.out- and gabc-gtex/bugs/fix-42-b.tex- differ
gabc-gtex/bugs/fix-42-c.gabc : FAIL - Files gabc-gtex/bugs/fix-42-c.gabc.out- and gabc-gtex/bugs/fix-42-c.tex- differ
gabc-gtex/bugs/fix-42-d.gabc : FAIL - Files gabc-gtex/bugs/fix-42-d.gabc.out- and gabc-gtex/bugs/fix-42-d.tex- differ
gabc-gtex/bugs/fix-42-e.gabc : FAIL - Files gabc-gtex/bugs/fix-42-e.gabc.out- and gabc-gtex/bugs/fix-42-e.tex- differ
gabc-gtex/bugs/fix-42-f.gabc : FAIL - Files gabc-gtex/bugs/fix-42-f.gabc.out- and gabc-gtex/bugs/fix-42-f.tex- differ
gabc-gtex/PopulusSion.gabc : FAIL - Files gabc-gtex/PopulusSion.gabc.out- and gabc-gtex/PopulusSion.tex- differ
gabc-gtex/sample.gabc : FAIL - Files gabc-gtex/sample.gabc.out- and gabc-gtex/sample.tex- differ
gabc-gtex/signs/46-55.gabc : FAIL - Files gabc-gtex/signs/46-55.gabc.out- and gabc-gtex/signs/46-55.tex- differ
gabc-dump/bugs/fix-135.gabc : FAIL - Files gabc-dump/bugs/fix-135.gabc.out- and gabc-dump/bugs/fix-135.dump- differ
gabc-dump/bugs/fix-20.gabc : FAIL - Files gabc-dump/bugs/fix-20.gabc.out- and gabc-dump/bugs/fix-20.dump- differ
gabc-dump/bugs/fix-42-b.gabc : FAIL - Files gabc-dump/bugs/fix-42-b.gabc.out- and gabc-dump/bugs/fix-42-b.dump- differ
gabc-dump/bugs/fix-42-c.gabc : FAIL - Files gabc-dump/bugs/fix-42-c.gabc.out- and gabc-dump/bugs/fix-42-c.dump- differ
gabc-dump/bugs/fix-42-d.gabc : FAIL - Files gabc-dump/bugs/fix-42-d.gabc.out- and gabc-dump/bugs/fix-42-d.dump- differ
gabc-dump/bugs/fix-42-e.gabc : FAIL - Files gabc-dump/bugs/fix-42-e.gabc.out- and gabc-dump/bugs/fix-42-e.dump- differ
gabc-dump/bugs/fix-42-f.gabc : FAIL - Files gabc-dump/bugs/fix-42-f.gabc.out- and gabc-dump/bugs/fix-42-f.dump- differ
gabc-dump/glyphs/above_lines_text.gabc : FAIL - Files gabc-dump/glyphs/above_lines_text.gabc.out- and gabc-dump/glyphs/above_lines_text.dump- differ
gabc-dump/glyphs/bars.gabc : FAIL - Files gabc-dump/glyphs/bars.gabc.out- and gabc-dump/glyphs/bars.dump- differ
gabc-dump/glyphs/clef_change.gabc : FAIL - Files gabc-dump/glyphs/clef_change.gabc.out- and gabc-dump/glyphs/clef_change.dump- differ
gabc-dump/glyphs/comments.gabc : FAIL - Files gabc-dump/glyphs/comments.gabc.out- and gabc-dump/glyphs/comments.dump- differ
gabc-dump/glyphs/other.gabc : FAIL - Files gabc-dump/glyphs/other.gabc.out- and gabc-dump/glyphs/other.dump- differ
gabc-dump/glyphs/quilisma.gabc : FAIL - Files gabc-dump/glyphs/quilisma.gabc.out- and gabc-dump/glyphs/quilisma.dump- differ
gabc-dump/glyphs/rare.gabc : FAIL - Files gabc-dump/glyphs/rare.gabc.out- and gabc-dump/glyphs/rare.dump- differ
gabc-dump/glyphs/repercussion.gabc : FAIL - Files gabc-dump/glyphs/repercussion.gabc.out- and gabc-dump/glyphs/repercussion.dump- differ
gabc-dump/glyphs/stemmed_oriscus.gabc : FAIL - Files gabc-dump/glyphs/stemmed_oriscus.gabc.out- and gabc-dump/glyphs/stemmed_oriscus.dump- differ
gabc-dump/glyphs/verbatim.gabc : FAIL - Files gabc-dump/glyphs/verbatim.gabc.out- and gabc-dump/glyphs/verbatim.dump- differ
gabc-dump/test_all_headers.gabc : FAIL - Files gabc-dump/test_all_headers.gabc.out- and gabc-dump/test_all_headers.dump- differ
gabc-output/bugs/fix-18.gabc : FAIL - [gabc-output/bugs/fix-18.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-243.gabc : FAIL - [gabc-output/bugs/fix-243.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-246-peron.gabc : FAIL - [gabc-output/bugs/fix-246-peron.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-246.gabc : FAIL - [gabc-output/bugs/fix-246.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-284.gabc : FAIL - [gabc-output/bugs/fix-284.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-347.gabc : FAIL - [gabc-output/bugs/fix-347.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-70.gabc : FAIL - [gabc-output/bugs/fix-70.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-gna-21737.gabc : FAIL - [gabc-output/bugs/fix-gna-21737.gabc.out/page.png] differ from expected
gabc-output/bugs/test75a.gabc : FAIL - [gabc-output/bugs/test75a.gabc.out/page.png] differ from expected
gabc-output/bugs/test75b.gabc : FAIL - [gabc-output/bugs/test75b.gabc.out/page.png] differ from expected
gabc-output/bugs/test78.gabc : FAIL - [gabc-output/bugs/test78.gabc.out/page.png] differ from expected
gabc-output/bugs/test79.gabc : FAIL - [gabc-output/bugs/test79.gabc.out/page.png] differ from expected
gabc-output/bugs/test82.gabc : FAIL - [gabc-output/bugs/test82.gabc.out/page.png] differ from expected
gabc-output/bugs/test84.gabc : FAIL - [gabc-output/bugs/test84.gabc.out/page.png] differ from expected
gabc-output/bugs/test98.gabc : FAIL - [gabc-output/bugs/test98.gabc.out/page.png] differ from expected
gabc-output/glyphs/above_lines_text.gabc : FAIL - [gabc-output/glyphs/above_lines_text.gabc.out/page.png] differ from expected
gabc-output/glyphs/accidentals.gabc : FAIL - [gabc-output/glyphs/accidentals.gabc.out/page.png] differ from expected
gabc-output/glyphs/bars.gabc : FAIL - [gabc-output/glyphs/bars.gabc.out/page.png] differ from expected
gabc-output/glyphs/choral_signs.gabc : FAIL - [gabc-output/glyphs/choral_signs.gabc.out/page.png] differ from expected
gabc-output/glyphs/clef_change.gabc : FAIL - [gabc-output/glyphs/clef_change.gabc.out/page.png] differ from expected
gabc-output/glyphs/clivis.gabc : FAIL - [gabc-output/glyphs/clivis.gabc.out/page-0.png gabc-output/glyphs/clivis.gabc.out/page-1.png] differ from expected
gabc-output/glyphs/comments.gabc : FAIL - [gabc-output/glyphs/comments.gabc.out/page.png] differ from expected
gabc-output/glyphs/divisio_finalis.gabc : FAIL - [gabc-output/glyphs/divisio_finalis.gabc.out/page.png] differ from expected
gabc-output/glyphs/horizontal_episemus.gabc : FAIL - [gabc-output/glyphs/horizontal_episemus.gabc.out/page.png] differ from expected
gabc-output/glyphs/horizontal_episemus_bridges.gabc : FAIL - [gabc-output/glyphs/horizontal_episemus_bridges.gabc.out/page.png] differ from expected
gabc-output/glyphs/limits.gabc : FAIL - [gabc-output/glyphs/limits.gabc.out/page.png] differ from expected
gabc-output/glyphs/macros.gabc : FAIL - [gabc-output/glyphs/macros.gabc.out/page.png] differ from expected
gabc-output/glyphs/melismatic.gabc : FAIL - [gabc-output/glyphs/melismatic.gabc.out/page.png] differ from expected
gabc-output/glyphs/oriscus.gabc : FAIL - [gabc-output/glyphs/oriscus.gabc.out/page.png] differ from expected
gabc-output/glyphs/other.gabc : FAIL - [gabc-output/glyphs/other.gabc.out/page.png] differ from expected
gabc-output/glyphs/over_braces.gabc : FAIL - [gabc-output/glyphs/over_braces.gabc.out/page.png] differ from expected
gabc-output/glyphs/pes.gabc : FAIL - [gabc-output/glyphs/pes.gabc.out/page-0.png gabc-output/glyphs/pes.gabc.out/page-1.png] differ from expected
gabc-output/glyphs/pitches.gabc : FAIL - [gabc-output/glyphs/pitches.gabc.out/page.png] differ from expected
gabc-output/glyphs/porrectus.gabc : FAIL - [gabc-output/glyphs/porrectus.gabc.out/page.png] differ from expected
gabc-output/glyphs/quilisma.gabc : FAIL - [gabc-output/glyphs/quilisma.gabc.out/page.png] differ from expected
gabc-output/glyphs/rare.gabc : FAIL - [gabc-output/glyphs/rare.gabc.out/page.png] differ from expected
gabc-output/glyphs/repercussion.gabc : FAIL - [gabc-output/glyphs/repercussion.gabc.out/page.png] differ from expected
gabc-output/glyphs/salicus.gabc : FAIL - [gabc-output/glyphs/salicus.gabc.out/page.png] differ from expected
gabc-output/glyphs/shapes.gabc : FAIL - [gabc-output/glyphs/shapes.gabc.out/page.png] differ from expected
gabc-output/glyphs/spaces.gabc : FAIL - [gabc-output/glyphs/spaces.gabc.out/page.png] differ from expected
gabc-output/glyphs/stemmed_oriscus.gabc : FAIL - [gabc-output/glyphs/stemmed_oriscus.gabc.out/page.png] differ from expected
gabc-output/glyphs/styles.gabc : FAIL - [gabc-output/glyphs/styles.gabc.out/page.png] differ from expected
gabc-output/glyphs/torculus.gabc : FAIL - [gabc-output/glyphs/torculus.gabc.out/page.png] differ from expected
gabc-output/glyphs/torculus_resupinus.gabc : FAIL - [gabc-output/glyphs/torculus_resupinus.gabc.out/page.png] differ from expected
gabc-output/glyphs/torculus_resupinus_flexus.gabc : FAIL - [gabc-output/glyphs/torculus_resupinus_flexus.gabc.out/page.png] differ from expected
gabc-output/glyphs/torculus_resupinus_quilisma.gabc : FAIL - [gabc-output/glyphs/torculus_resupinus_quilisma.gabc.out/page.png] differ from expected
gabc-output/glyphs/translation.gabc : FAIL - [gabc-output/glyphs/translation.gabc.out/page.png] differ from expected
gabc-output/glyphs/verbatim.gabc : FAIL - [gabc-output/glyphs/verbatim.gabc.out/page.png] differ from expected
gabc-output/sample.gabc : FAIL - [gabc-output/sample.gabc.out/page.png] differ from expected
tex-output/bugs/fix-60/fix-60.tex : FAIL - [tex-output/bugs/fix-60/fix-60.tex.out/page.png] differ from expected
tex-output/change-glyph/change-glyph.tex : FAIL - [tex-output/change-glyph/change-glyph.tex.out/page.png] differ from expected
tex-output/PopulusSion/PopulusSion.tex : FAIL - [tex-output/PopulusSion/PopulusSion.tex.out/page.png] differ from expected
tex-output/sample/sample.tex : FAIL - [tex-output/sample/sample.tex.out/page.png] differ from expected
tex-output/sign-styles/sign-styles.tex : FAIL - [tex-output/sign-styles/sign-styles.tex.out/page.png] differ from expected
tex-output/snippet/snippet.tex : FAIL - [tex-output/snippet/snippet.tex.out/page.png] differ from expected
tex-output/symbols/symbols.tex : FAIL - [tex-output/symbols/symbols.tex.out/page.png] differ from expected
tex-output/translation/translation.tex : FAIL - [tex-output/translation/translation.tex.out/page.png] differ from expected
plain-tex/braces/over_braces.tex : FAIL - [plain-tex/braces/over_braces.tex.out/page.png] differ from expected
plain-tex/PopulusSion/PopulusSion.tex : FAIL - [plain-tex/PopulusSion/PopulusSion.tex.out/page.png] differ from expected

real	8m44.050s
user	5m58.648s
sys	0m29.821s

SOMETHING FAILED
```
I don't know if that's every test, but it does appear that at least every sort of test (including gabc->gtex and gabc dump) tests are failing.

**Comment by henryso** [comment]
That does look like pretty much every test.  I am going to need some more information.  Could you send me the following files?  Email is fine.

- output/gabc-gtex/PopulusSion.gabc.out-
- output/gabc-gtex/PopulusSion.tex-
- output/gabc-dump/bugs/fix-42-b.gabc.out-
- output/gabc-dump/bugs/fix-42-b.dump-
- output/gabc-output/glyphs/melismatic.gabc.out/page.png
- output/gabc-output/glyphs/meliismatic.gabc.out/melismatic.pdf
- output/tex-output/PopulusSion/PopulusSion.tex.out/page.png
- output/tex-output/PopulusSion/PopulusSion.tex.out/PopulusSion.pdf

**Comment by rpspringuel** [comment]
Check your inbox.

**Comment by henryso** [comment]
`sed` is not acting the way I expect it to act on your computer.  This is the reason the gabc-gtex and gabc-dump tests are failing.  I'll see if I can figure it out, but if you have any hints (look at `harness.sh`, at around lines 185 and 229), I'm all ears.   Maybe the regular expression language in the Mac version of sed is different.  The PDF breakages are minor differences in rendering.  That's what I was afraid of.  Let me see if there is a fudge factor I can work in.

**Comment by rpspringuel** [comment]
The `sed` that comes by default with a Mac does work differently, particular on expanded regular expressions.  I do have the GNU version, but it's under `gsed`.  Is there a flag in the script that would allow me to tell the script where to find the GNU version, or could you add one?

**Comment by henryso** [comment]
I added a configurable variable for `sed`.  It's called (unsurprisingly) `SED` and may be set in the environment or in the `gregorio-test.rc` file.  I also apparently forgot to push the latest test updates, which went up when I pushed this.

The PDF problem is more perplexing.  It seems like the PDF you produce has fonts that are "lighter" (though not necessarily less bold).  I wonder if that's just a function of how lua renders fonts on different operating systems.  If so, I think I/we need to figure out a better way to prepare or compare the PDFs.

**Comment by eroux** [comment]
IIRC, XeTeX used to have a different rendering engine before using harfbuzz, but LuaTeX has its own rendering engine (in lua) that shouldn't be different from one os to another... But different luaotfload versions (and thus different rendering engines) might cause this...

**Comment by rpspringuel** [comment]
With the following `gregorio-test.rc` file I'm still getting nearly blanket test failures:
```
# this is a shell script fragment
SED=gsed
COLOR=true
```
Have I got the syntax right for setting the `SED` option?

**Comment by henryso** [comment]
That should be right.  Can you send me the `out-`, `tex-`, and `dump-` files again?

On a separate note, I think the font problem has to do with the version of the font I have in my OS font directories.  I'll see if I can isolate the tests better..

**Comment by henryso** [comment]
@rpspringuel the files you sent compare identical, so I'm a bit confused.  If you run `diff` on `PopulusSion.gabc.out-` and `PopulusSion.tex-`, does it say they are different?  If it says they are the same, then I think the script that does the comparison is broken and will be a little difficult for me to debug without a Mac in front of me (but I will try).  In any case, I need to prepare for Mass, so I will be unavailable for about 2.5 hours from now.

On the fonts, I think it would be best for me to supply a specific set of fonts to use.  I'll work on that later tonight as well.

**Comment by rpspringuel** [comment]
`diff` returns nothing on those two files (which I think means they're identical.  Perhaps the list wasn't as complete as I thought.  Here's the specific output from the second test run:

```
Gregorio = /usr/local/bin/gregorio
GregorioTeX = /usr/local/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex.tex

gabc-dump/glyphs/above_lines_text.gabc : FAIL - Files gabc-dump/glyphs/above_lines_text.gabc.out- and gabc-dump/glyphs/above_lines_text.dump- differ
gabc-dump/glyphs/verbatim.gabc : FAIL - Files gabc-dump/glyphs/verbatim.gabc.out- and gabc-dump/glyphs/verbatim.dump- differ
gabc-output/bugs/fix-18.gabc : FAIL - [gabc-output/bugs/fix-18.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-243.gabc : FAIL - [gabc-output/bugs/fix-243.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-246-peron.gabc : FAIL - [gabc-output/bugs/fix-246-peron.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-246.gabc : FAIL - [gabc-output/bugs/fix-246.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-284.gabc : FAIL - [gabc-output/bugs/fix-284.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-347.gabc : FAIL - [gabc-output/bugs/fix-347.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-70.gabc : FAIL - [gabc-output/bugs/fix-70.gabc.out/page.png] differ from expected
gabc-output/bugs/fix-gna-21737.gabc : FAIL - [gabc-output/bugs/fix-gna-21737.gabc.out/page.png] differ from expected
gabc-output/bugs/test75a.gabc : FAIL - [gabc-output/bugs/test75a.gabc.out/page.png] differ from expected
gabc-output/bugs/test75b.gabc : FAIL - [gabc-output/bugs/test75b.gabc.out/page.png] differ from expected
gabc-output/bugs/test78.gabc : FAIL - [gabc-output/bugs/test78.gabc.out/page.png] differ from expected
gabc-output/bugs/test79.gabc : FAIL - [gabc-output/bugs/test79.gabc.out/page.png] differ from expected
gabc-output/bugs/test82.gabc : FAIL - [gabc-output/bugs/test82.gabc.out/page.png] differ from expected
gabc-output/bugs/test84.gabc : FAIL - [gabc-output/bugs/test84.gabc.out/page.png] differ from expected
gabc-output/bugs/test98.gabc : FAIL - [gabc-output/bugs/test98.gabc.out/page.png] differ from expected
gabc-output/glyphs/above_lines_text.gabc : FAIL - [gabc-output/glyphs/above_lines_text.gabc.out/page.png] differ from expected
gabc-output/glyphs/accidentals.gabc : FAIL - [gabc-output/glyphs/accidentals.gabc.out/page.png] differ from expected
gabc-output/glyphs/bars.gabc : FAIL - [gabc-output/glyphs/bars.gabc.out/page.png] differ from expected
gabc-output/glyphs/choral_signs.gabc : FAIL - [gabc-output/glyphs/choral_signs.gabc.out/page.png] differ from expected
gabc-output/glyphs/clef_change.gabc : FAIL - [gabc-output/glyphs/clef_change.gabc.out/page.png] differ from expected
gabc-output/glyphs/clivis.gabc : FAIL - [gabc-output/glyphs/clivis.gabc.out/page-0.png gabc-output/glyphs/clivis.gabc.out/page-1.png] differ from expected
gabc-output/glyphs/comments.gabc : FAIL - [gabc-output/glyphs/comments.gabc.out/page.png] differ from expected
gabc-output/glyphs/divisio_finalis.gabc : FAIL - [gabc-output/glyphs/divisio_finalis.gabc.out/page.png] differ from expected
gabc-output/glyphs/horizontal_episemus.gabc : FAIL - [gabc-output/glyphs/horizontal_episemus.gabc.out/page.png] differ from expected
gabc-output/glyphs/horizontal_episemus_bridges.gabc : FAIL - [gabc-output/glyphs/horizontal_episemus_bridges.gabc.out/page.png] differ from expected
gabc-output/glyphs/limits.gabc : FAIL - [gabc-output/glyphs/limits.gabc.out/page.png] differ from expected
gabc-output/glyphs/macros.gabc : FAIL - [gabc-output/glyphs/macros.gabc.out/page.png] differ from expected
gabc-output/glyphs/melismatic.gabc : FAIL - [gabc-output/glyphs/melismatic.gabc.out/page.png] differ from expected
gabc-output/glyphs/oriscus.gabc : FAIL - [gabc-output/glyphs/oriscus.gabc.out/page.png] differ from expected
gabc-output/glyphs/other.gabc : FAIL - [gabc-output/glyphs/other.gabc.out/page.png] differ from expected
gabc-output/glyphs/over_braces.gabc : FAIL - [gabc-output/glyphs/over_braces.gabc.out/page.png] differ from expected
gabc-output/glyphs/pes.gabc : FAIL - [gabc-output/glyphs/pes.gabc.out/page-0.png gabc-output/glyphs/pes.gabc.out/page-1.png] differ from expected
gabc-output/glyphs/pitches.gabc : FAIL - [gabc-output/glyphs/pitches.gabc.out/page.png] differ from expected
gabc-output/glyphs/porrectus.gabc : FAIL - [gabc-output/glyphs/porrectus.gabc.out/page.png] differ from expected
gabc-output/glyphs/quilisma.gabc : FAIL - [gabc-output/glyphs/quilisma.gabc.out/page.png] differ from expected
gabc-output/glyphs/rare.gabc : FAIL - [gabc-output/glyphs/rare.gabc.out/page.png] differ from expected
gabc-output/glyphs/repercussion.gabc : FAIL - [gabc-output/glyphs/repercussion.gabc.out/page.png] differ from expected
gabc-output/glyphs/salicus.gabc : FAIL - [gabc-output/glyphs/salicus.gabc.out/page.png] differ from expected
gabc-output/glyphs/shapes.gabc : FAIL - [gabc-output/glyphs/shapes.gabc.out/page.png] differ from expected
gabc-output/glyphs/spaces.gabc : FAIL - [gabc-output/glyphs/spaces.gabc.out/page.png] differ from expected
gabc-output/glyphs/stemmed_oriscus.gabc : FAIL - [gabc-output/glyphs/stemmed_oriscus.gabc.out/page.png] differ from expected
gabc-output/glyphs/styles.gabc : FAIL - [gabc-output/glyphs/styles.gabc.out/page.png] differ from expected
gabc-output/glyphs/torculus.gabc : FAIL - [gabc-output/glyphs/torculus.gabc.out/page.png] differ from expected
gabc-output/glyphs/torculus_resupinus.gabc : FAIL - [gabc-output/glyphs/torculus_resupinus.gabc.out/page.png] differ from expected
gabc-output/glyphs/torculus_resupinus_flexus.gabc : FAIL - [gabc-output/glyphs/torculus_resupinus_flexus.gabc.out/page.png] differ from expected
gabc-output/glyphs/torculus_resupinus_quilisma.gabc : FAIL - [gabc-output/glyphs/torculus_resupinus_quilisma.gabc.out/page.png] differ from expected
gabc-output/glyphs/translation.gabc : FAIL - [gabc-output/glyphs/translation.gabc.out/page.png] differ from expected
gabc-output/glyphs/verbatim.gabc : FAIL - [gabc-output/glyphs/verbatim.gabc.out/page.png] differ from expected
gabc-output/sample.gabc : FAIL - [gabc-output/sample.gabc.out/page.png] differ from expected
tex-output/bugs/fix-60/fix-60.tex : FAIL - [tex-output/bugs/fix-60/fix-60.tex.out/page.png] differ from expected
tex-output/change-glyph/change-glyph.tex : FAIL - [tex-output/change-glyph/change-glyph.tex.out/page.png] differ from expected
tex-output/PopulusSion/PopulusSion.tex : FAIL - [tex-output/PopulusSion/PopulusSion.tex.out/page.png] differ from expected
tex-output/sample/sample.tex : FAIL - [tex-output/sample/sample.tex.out/page.png] differ from expected
tex-output/sign-styles/sign-styles.tex : FAIL - [tex-output/sign-styles/sign-styles.tex.out/page.png] differ from expected
tex-output/snippet/snippet.tex : FAIL - [tex-output/snippet/snippet.tex.out/page.png] differ from expected
tex-output/symbols/symbols.tex : FAIL - [tex-output/symbols/symbols.tex.out/page.png] differ from expected
tex-output/translation/translation.tex : FAIL - [tex-output/translation/translation.tex.out/page.png] differ from expected
plain-tex/braces/over_braces.tex : FAIL - [plain-tex/braces/over_braces.tex.out/page.png] differ from expected
plain-tex/PopulusSion/PopulusSion.tex : FAIL - [plain-tex/PopulusSion/PopulusSion.tex.out/page.png] differ from expected

real	7m50.931s
user	5m59.106s
sys	0m28.236s

SOMETHING FAILED
```

**Comment by henryso** [comment]
There are only two dumps failing.  If you can send me the `out-` and `dump-` files for them, I'll take a look when I'm back home.  The rest are are most likely due to the font issue.  I'll try to have something for you to try by tomorrow morning.

**Comment by henryso** [comment]
@rpspringuel I've updated the tests to (hopefully) use a font that I bundled to lock the version down.  I'm hoping that this fixes the PDF tests for you, so please try it when you have a chance.

**Comment by rpspringuel** [comment]
Testing this morning against:
```
Gregorio version 3.0.1-develop-7e5d3b3-2040.
Copyright (C) 2006-2015 Gregorio project authors (see CONTRIBUTORS.md)
```
I get the following output:
```
Gregorio = /usr/local/bin/gregorio
GregorioTeX = /usr/local/texlive/texmf-local/tex/luatex/gregoriotex/gregoriotex.tex

_: line 1:  3595 Segmentation fault: 11  gregorio -f gabc -F dump -o "$outfile" -l "$logfile" "$filename"
gabc-dump/first_syllable/styled-no-initial-special.gabc : FAIL - Failed to compile gabc-dump/first_syllable/styled-no-initial-special.gabc
gabc-dump/glyphs/above_lines_text.gabc : FAIL - Files gabc-dump/glyphs/above_lines_text.gabc.out- and gabc-dump/glyphs/above_lines_text.dump- differ
gabc-dump/glyphs/verbatim.gabc : FAIL - Files gabc-dump/glyphs/verbatim.gabc.out- and gabc-dump/glyphs/verbatim.dump- differ
plain-tex/braces/over_braces.tex : FAIL - [plain-tex/braces/over_braces.tex.out/page.png] differ from expected
plain-tex/PopulusSion/PopulusSion.tex : FAIL - [plain-tex/PopulusSion/PopulusSion.tex.out/page.png] differ from expected

real	7m16.963s
user	6m1.814s
sys	0m26.471s

SOMETHING FAILED
```
It's clearly a much shorter list, so locking down the fonts had a significant effect.  I've emailed the `out-` and `dump-` files for the two dump tests that failed based on differing files.  If you need anything else, let me know.

**Comment by henryso** [comment]
The dumps are failing because somehow my local repository differs against the one on github (and refuses to believe there are any changes).  I pulled a fresh clone and fixed the expectations.  This is now corrected.

The segfault is serious, but I can't reproduce it (even using a freshly cloned repository).  Are you able to debug the executable to find out on which line it's faulting against `styled-no-initial-special.gabc`?

**Comment by henryso** [comment]
I found one bug in the `gregorio_note` structure, but I doubt this is the cause of the segfault, but in any case, I committed that and merged it.

**Comment by rpspringuel** [comment]
The segmentation fault appears to be occuring in the `if` statement in `gabc_dump_test`  I'm not sure why the segmentation fault should occur on that test and not any others, but I can confirm that running the gregorio command in that `if` statement independently from the command line reproduces the fault.

Playing around with the gabc file, I note that I can eliminate the fault by modifying the gabc code.  Of course, all of the modifications I've tried so far that eliminate the fault, also eliminate what the test is trying to get at (the nesting of `<sp></sp>` tags within styling tags in the first syllable).  Since you can't duplicate the problem, it would appear to be system specific.

I'm also still failing on the two PlainTeX tests.  Checking the output folders, I note that the image size of the created page.png is different from that for the expected one.  Based on a visual inspection, it appears to be the difference between A4 paper and Letter.  The expected results has the aspect ratio of A4 while the stuff my system produces is Letter.

**Comment by henryso** [comment]
Thank you for finding the A4/Letter problem.  I have fixed the plain-tex tests to use A4 paper.

Are you able to run a debugger (like gdb, or somesuch) on the gregorio executable to find out on which line it is segfaulting?  It's most likely a latent bug that is evidenced by slightly different alignments in the data structures.  However, since I can't reproduce it, the best I can do alone is inspect code, which I have already done, but my eyes are only human and getting worse every day.

**Comment by rpspringuel** [comment]
I'll try to get to that tomorrow (assuming I can figure out how).

In the meantime, inspecting the output of my build process reveals the following two warnings:

```
gabc/gabc-score-determination-l.c:2535:17: warning: comparison of integers of
      different signs: 'int' and 'yy_size_t' (aka 'unsigned long')
      [-Wsign-compare]
        for ( i = 0; i < _yybytes_len; ++i )
                     ~ ^ ~~~~~~~~~~~~
1 warning generated.
```
and
```
gabc/gabc-notes-determination-l.c:8399:17: warning: comparison of integers of
      different signs: 'int' and 'yy_size_t' (aka 'unsigned long')
      [-Wsign-compare]
        for ( i = 0; i < _yybytes_len; ++i )
                     ~ ^ ~~~~~~~~~~~~
1 warning generated.
```

**Comment by henryso** [comment]
That's interesting.  On my computer, flex produces code which declares `i` as `yy_size_t`, so obviously I don't get that warning.  I am using flex 2.5.39.  Still, I don't think this is the cause of the problem, as `i` will always be positive in the loop (until the integer wraps around, but that would require a HUGE gabc file).

**Comment by henryso** [comment]
There's definitely a bug (in the first syllable handling code that I added yesterday) when `initial-style` is `0` and the score starts with a verbatim block or special character.  I may have a solution by morning.

**Comment by rpspringuel** [comment]
I have flex 2.5.37, which is the most recent version available via MacPorts.

**Comment by henryso** [comment]
I fixed the previously mentioned bug, merged the changes into gregorio:develop, and updated the tests here.

I think you'll just have to ignore the `sign-compare` warning.  That code is entirely coming from flex.

**Comment by rpspringuel** [comment]
All tests pass for 8baff04 against Gregorio version 3.0.1-develop-3786e33-2044.

**Comment by henryso** [comment]
Thank you so much for your help.  This makes me more confident that the tests will now work in multiple environments.

**Comment by rpspringuel** [comment]
No problem.  This actually helped me with my texrenaming work as getting the tests working enabled me to spot stuff I missed changing.
